# Generated by Django 6.0.6 on 2026-06-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslisting',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price/cost in local currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price/cost in local currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='operating_hours',
            field=models.CharField(blank=True, help_text='Operating hours (e.g., Mon-Fri 9AM-5PM)', max_length=300),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='price_unit',
            field=models.CharField(blank=True, default='per item', help_text='Price unit (e.g., per item, per hour, per kg)', max_length=100),
        ),
        migrations.AddField(
            model_name='businesslisting',
            name='requirements',
            field=models.TextField(blank=True, help_text='List business requirements, qualifications, or specifications'),
        ),
    ]
