"""
Django settings for SokoConnect project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^ei1%z$n%#^pee#r%0f%8me)koib*soia-vg2c7u_4mgp(b5l2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*.sokoconnect.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'business',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SokoConnect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SokoConnect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default auto field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Stripe Payment Configuration
# Get these from https://dashboard.stripe.com/apikeys
STRIPE_PUBLIC_KEY = 'pk_test_YOUR_PUBLIC_KEY_HERE'
STRIPE_SECRET_KEY = 'sk_test_YOUR_SECRET_KEY_HERE'
STRIPE_WEBHOOK_SECRET = 'whsec_test_YOUR_WEBHOOK_SECRET_HERE'  # From Webhook settings
STRIPE_BUSINESS_LISTING_PRICE = 5000  # $50.00 in cents
STRIPE_CURRENCY = 'usd'

# PayPal Configuration
PAYPAL_MODE = 'sandbox'  # Change to 'live' for production
PAYPAL_CLIENT_ID = 'YOUR_PAYPAL_CLIENT_ID'
PAYPAL_CLIENT_SECRET = 'YOUR_PAYPAL_CLIENT_SECRET'
PAYPAL_BUSINESS_LISTING_PRICE = '50.00'  # $50.00 USD
PAYPAL_CURRENCY = 'USD'

# M-Pesa Configuration (Safaricom Daraja API)
MPESA_CONSUMER_KEY = 'YOUR_MPESA_CONSUMER_KEY'
MPESA_CONSUMER_SECRET = 'YOUR_MPESA_CONSUMER_SECRET'
MPESA_SHORTCODE = 'YOUR_SHORTCODE'
MPESA_PASSKEY = 'YOUR_PASSKEY'
MPESA_CALLBACK_URL = 'https://yourdomain.com/api/mpesa-callback/'
MPESA_BUSINESS_LISTING_PRICE = '5000'  # 5000 KES
MPESA_CURRENCY = 'KES'
MPESA_ENVIRONMENT = 'sandbox'  # Change to 'production' for live

# Airtel Money Configuration (Tanzania)
AIRTEL_MONEY_API_KEY = 'YOUR_AIRTEL_API_KEY'
AIRTEL_MONEY_SECRET = 'YOUR_AIRTEL_SECRET'
AIRTEL_MONEY_SHORTCODE = 'YOUR_AIRTEL_SHORTCODE'
AIRTEL_MONEY_CALLBACK_URL = 'https://yourdomain.com/api/airtel-callback/'
AIRTEL_MONEY_BUSINESS_LISTING_PRICE = '5000'  # 5000 TZS
AIRTEL_MONEY_ENVIRONMENT = 'sandbox'  # Change to 'production' for live

# Tigo Pesa Configuration (Tanzania)
TIGO_PESA_API_KEY = 'YOUR_TIGO_API_KEY'
TIGO_PESA_SECRET = 'YOUR_TIGO_SECRET'
TIGO_PESA_SHORTCODE = 'YOUR_TIGO_SHORTCODE'
TIGO_PESA_CALLBACK_URL = 'https://yourdomain.com/api/tigo-callback/'
TIGO_PESA_BUSINESS_LISTING_PRICE = '5000'  # 5000 TZS
TIGO_PESA_ENVIRONMENT = 'sandbox'  # Change to 'production' for live

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development - prints to console
# For production, use:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
DEFAULT_FROM_EMAIL = 'noreply@sokoconnect.com'
